module.exports = {
  User: 'Guest',
  FacebookPicture: '../../textures/GuestPicture.png',
  Skins: [],
  ChosenSkin: null,
  color: 'teal',
  facebookid: null,
  stars: 0,
  hat: 'ha2.obj',
  maps: [
    {name: 'Fraggle Rock', thumb: '../../../textures/fraggleRockThumb.jpg'},
    {name: 'Dawn Mountain', thumb: '../../../textures/dawnmountainThumb.jpg'},
    {name: 'High Noon', thumb: '../../../textures/highNoonThumb.jpg'}
  ],
  map: 0,
  graphics: 2,
  winner: null,
  userId: null,
  skinsObj: {
      '/textures/skins/SmileyFace.jpg': {skinPic: '../../../textures/skins/SmileyFacePreview.jpg', skin: '/textures/skins/SmileyFace.jpg', name: 'Big Smile', price: 500},
      '/textures/skins/coolGuy.jpg': {skinPic: '../../../textures/skins/coolGuyPreview.jpg', skin: '/textures/skins/coolGuy.jpg', name: 'Cool Guy', price: 200},
      '/textures/skins/smile.jpg': {skinPic: '../../../textures/skins/smilePreview.jpg', skin: '/textures/skins/smile.jpg', name: 'Smiley', price: 100},
      '/textures/skins/silly.jpg': {skinPic: '../../../textures/skins/sillyPreview.jpg', skin: '/textures/skins/silly.jpg', name: 'Silly', price: 50},
      '/textures/skins/wink.jpg': {skinPic: '../../../textures/skins/winkPreview.jpg', skin: '/textures/skins/wink.jpg', name: 'Wink', price: 100},
      '/textures/skins/sidewaysSmile.jpg': {skinPic: '../../../textures/skins/sidewaysSmilePreview.jpg', skin: '/textures/skins/sidewaysSmile.jpg', name: 'Sideways Smile', price: 100},
      '/textures/skins/twirlyStache.jpg': {skinPic: '../../../textures/skins/twirlyStachePreview.jpg', skin: '/textures/skins/twirlyStache.jpg', name: 'Twirly Stache', price: 200},
      '/textures/skins/googlyStache.jpg': {skinPic: '../../../textures/skins/googlyStachePreview.jpg', skin: '/textures/skins/googlyStache.jpg', name: 'Googly Stache', price: 300},
      '/textures/skins/gangstaStache.jpg': {skinPic: '../../../textures/skins/gangstaStachePreview.jpg', skin: '/textures/skins/gangstaStache.jpg', name: 'Gangsta Stache', price: 400},
      '/textures/skins/heisenberg.jpg': {skinPic: '../../../textures/skins/heisenbergPreview.jpg', skin: '/textures/skins/heisenberg.jpg', name: 'Heisenberg', price: 300},
      '/textures/skins/heisenbergHardcore.jpg': {skinPic: '../../../textures/skins/heisenbergHardcorePreview.jpg', skin: '/textures/skins/heisenbergHardcore.jpg', name: 'Hardcore', price: 500},
      '/textures/skins/glassesStache.jpg': {skinPic: '../../../textures/skins/glassesStachePreview.jpg', skin: '/textures/skins/glassesStache.jpg', name: 'Glasses N Stache', price: 500},
      '/textures/skins/soccer.jpg': {skinPic: '../../../textures/skins/SoccerBallPreview.jpg', skin: '/textures/skins/soccer.jpg', name: 'Socer Ball', price: 50},
      '/textures/skins/superman.jpg': {skinPic: '../../../textures/skins/superManPreview.jpg', skin: '/textures/skins/superman.jpg', name: 'Superman', price: 400},
      '/textures/skins/Batman.jpg': {skinPic: '../../../textures/skins/batmanPreview.jpg', skin: '/textures/skins/Batman.jpg', name: 'Batman', price: 400},
      '/textures/skins/8ball.jpg': {skinPic: '../../../textures/skins/8BallPreview.jpg', skin: '/textures/skins/8ball.jpg', name: '8 Ball', price: 250},
      '/textures/skins/CaptainAmerica.jpg': {skinPic: '../../../textures/skins/CaptainAmericaPreview.jpg', skin: '/textures/skins/CaptainAmerica.jpg', name: 'Captain America', price: 400},
      'ha2.obj': {skinPic: '../../../textures/Skins/hatPreview.jpg', skin: 'ha2.obj', name: 'The Hat', price: 1500, type: 'hat'}
    },
  sound: 1,
  maxPlayers: null,
  createMatch: false,
  matchId: null,
  // scoreBoard: [{username: 'Chimpanzee', score: 800}, {username: 'Michael', score: 734}, {username: 'jimmy', score: 13}, {username: 'scorebit', score: 0}],
  scoreBoard: [],
  storeSkins: [
  {skinPic: '../../../textures/skins/SmileyFacePreview.jpg', skin: '/textures/skins/SmileyFace.jpg', name: 'Big Smile', price: 500, owned: false},
  {skinPic: '../../../textures/skins/coolGuyPreview.jpg', skin: '/textures/skins/coolGuy.jpg', name: 'Cool Guy', price: 300, owned: false},
  {skinPic: '../../../textures/skins/smilePreview.jpg', skin: '/textures/skins/smile.jpg', name: 'Smiley', price: 100, owned: false},
  {skinPic: '../../../textures/skins/sillyPreview.jpg', skin: '/textures/skins/silly.jpg', name: 'Silly', price: 150, owned: false},
  {skinPic: '../../../textures/skins/winkPreview.jpg', skin: '/textures/skins/wink.jpg', name: 'Wink', price: 100, owned: false},
  {skinPic: '../../../textures/skins/sidewaysSmilePreview.jpg', skin: '/textures/skins/sidewaysSmile.jpg', name: 'Sideways Smile', price: 50, owned: false},
  {skinPic: '../../../textures/skins/twirlyStachePreview.jpg', skin: '/textures/skins/twirlyStache.jpg', name: 'Twirly Stache', price: 300, owned: false},
  {skinPic: '../../../textures/skins/googlyStachePreview.jpg', skin: '/textures/skins/googlyStache.jpg', name: 'Googly Stache', price: 300, owned: false},
  {skinPic: '../../../textures/skins/gangstaStachePreview.jpg', skin: '/textures/skins/gangstaStache.jpg', name: 'Gangsta Stache', price: 400, owned: false},
  {skinPic: '../../../textures/skins/heisenbergPreview.jpg', skin: '/textures/skins/heisenberg.jpg', name: 'Heisenberg', price: 300, owned: false},
  {skinPic: '../../../textures/skins/heisenbergHardcorePreview.jpg', skin: '/textures/skins/heisenbergHardcore.jpg', name: 'Hardcore', price: 500, owned: false},
  {skinPic: '../../../textures/skins/glassesStachePreview.jpg', skin: '/textures/skins/glassesStache.jpg', name: 'Glasses N Stache', price: 500, owned: false},
  {skinPic: '../../../textures/skins/SoccerBallPreview.jpg', skin: '/textures/skins/soccer.jpg', name: 'Soccer Ball', price: 250, owned: false},
  {skinPic: '../../../textures/skins/superManPreview.jpg', skin: '/textures/skins/superman.jpg', name: 'Superman', price: 400, owned: false},
  {skinPic: '../../../textures/skins/batmanPreview.jpg', skin: '/textures/skins/Batman.jpg', name: 'Batman', price: 400, owned: false},
  {skinPic: '../../../textures/skins/8BallPreview.jpg', skin: '/textures/skins/8ball.jpg', name: '8 Ball', price: 250, owned: false},
  {skinPic: '../../../textures/skins/CaptainAmericaPreview.jpg', skin: '/textures/skins/CaptainAmerica.jpg', name: 'Captain America', price: 400, owned: false},
  {skinPic: '../../../textures/Skins/hatPreview.jpg', skin: 'ha2.obj', name: 'The Hat', price: 1500, type: 'hat', owned: false}
  ],
}
